name=UANIMA
version=1.0.0
author=Jonathan Mejorado López, Cesar Bautista <cesar.bautista@uelectronics.com>
maintainer=Jonathan Mejorado López, Cesar Bautista <cesar.bautista@uelectronics.com>
sentence=Arduino library for Neopixel addressable RGB LEDs
paragraph=A lightweight library providing basic effects and animations for addressable RGB LED strips (Neopixels)
category=Display
url=https://github.com/UNIT-Electronics-MX/unit_uanima_library
architectures=*
depends=Adafruit NeoPixel